# Generated by Django 6.0.5 on 2026-05-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('preset', 'Predeterminada'), ('custom', 'Personalizada')], max_length=10)),
                ('completada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Historial de alertas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_trabajo', models.PositiveIntegerField(default=30)),
                ('duracion_descanso', models.PositiveIntegerField(default=5)),
                ('mensaje_custom', models.CharField(blank=True, default='', max_length=120)),
                ('sonido_activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Configuración de alerta',
            },
        ),
    ]
