# Generated by Django 6.0.5 on 2026-06-24 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialalerta',
            name='ear_valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialalerta',
            name='parpadeos_minuto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialalerta',
            name='recomendacion_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historialalerta',
            name='tipo',
            field=models.CharField(choices=[('preset', 'Predeterminada'), ('custom', 'Personalizada'), ('avanzado', 'Modo Avanzado')], max_length=10),
        ),
        migrations.CreateModel(
            name='SesionAvanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('total_alertas', models.PositiveIntegerField(default=0)),
                ('ear_promedio', models.FloatField(blank=True, null=True)),
                ('parpadeos_promedio', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_avanzadas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Sesión avanzada',
                'verbose_name_plural': 'Sesiones avanzadas',
                'ordering': ['-inicio'],
            },
        ),
    ]
