# Generated by Django 6.0.5 on 2026-06-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historialalerta_ear_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
